- defaultTab: nodes
  description: pull docker images from dockerhub and run docker images perfectly
  executionEnabled: true
  id: 8eb64841-d14e-4c86-9a7e-a3ea08dfd0cd
  loglevel: INFO
  name: outgoing deployment
  nodeFilterEditable: false
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  sequence:
    commands:
    - description: shell file for run
      script: |
        #!/bin/bash
        docker stop  $(docker ps -aq)
        docker rm  $(docker ps -aq)
        docker rmi -f m0hitbansal/outgoing-webapp
        docker pull m0hitbansal/outgoing-sql
        docker pull m0hitbansal/outgoing-webapp
    keepgoing: false
    strategy: node-first
  uuid: 8eb64841-d14e-4c86-9a7e-a3ea08dfd0cd
